name: ModePile Pack CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 0xfc963f18dc21/doc-project-images:wacc
    steps:
      - name: Clone the Pack
        uses: actions/checkout@v4
      - name: Build the Pack
        run: sh ./ci-build-task.sh
      - name: Export the built class files
        uses: actions/upload-artifact@v4
        with:
          name: bin-classes
          path: ./bin
